# Generated by Django 4.2.6 on 2023-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pagamento_compra', models.CharField(choices=[('Pix', '1'), ('C.Débito', '2'), ('C.Crédito', '3')], max_length=9)),
            ],
        ),
    ]
