# Generated by Django 4.2.6 on 2023-11-06 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pagamento_compra', models.CharField(choices=[('1', 'Pix'), ('2', 'C.Débito'), ('3', 'C.Crédito')], max_length=9)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.bebida')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.pizza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
