# Generated by Django 4.2.6 on 2023-10-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionar_pedido', models.BooleanField(blank=True, null=True)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.bebida')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pagamento_compra', models.CharField(choices=[('Pix', 'Pix'), ('C.Débito', 'C.Débito'), ('C.Crédito', 'C.Crédito')], max_length=9)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido')),
            ],
        ),
    ]
