# Generated by Django 4.2.6 on 2023-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=100)),
                ('endereço_fornecedor', models.TextField()),
                ('telefone_fornecedor', models.CharField(max_length=100)),
                ('email_fornecedor', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('quantidade_produto', models.IntegerField()),
                ('validade_produto', models.DateField(blank=True, null=True)),
                ('codigo_produto', models.IntegerField()),
            ],
        ),
    ]
