# Generated by Django 4.2.6 on 2023-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bebida', models.CharField(max_length=50)),
                ('ml_bebida', models.IntegerField()),
                ('quantidade_bebida', models.IntegerField()),
                ('imagem_refri', models.ImageField(upload_to='foto_refri')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor_pizza', models.CharField(max_length=50, verbose_name='Sabor da Pizza')),
                ('tamamho_pizza', models.CharField(choices=[('F', 'Família'), ('G', 'Grande'), ('M', 'Média'), ('p', 'pequena'), ('B', 'Brotinho')], max_length=8, verbose_name='Tamanho da Pizza')),
                ('descricao_pizza', models.TextField(verbose_name='Descrição da Pizza')),
                ('quantidade_pizza', models.IntegerField(verbose_name='quantidade')),
                ('imagem_pizza', models.ImageField(upload_to='foto_pizza')),
            ],
        ),
    ]
