# Generated by Django 4.2.6 on 2023-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bebida', models.CharField(max_length=50)),
                ('ml_bebida', models.IntegerField()),
                ('quantidade_bebida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_pedido', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pizza', models.CharField(max_length=100)),
                ('sabor_pizza', models.CharField(max_length=50)),
                ('tamamho_pizza', models.CharField(choices=[('M', 'Média'), ('B', 'Brotinho'), ('G', 'Grande'), ('F', 'Família'), ('p', 'pequena')], max_length=1)),
                ('descricao_pizza', models.TextField()),
                ('quantidade_pizza', models.IntegerField()),
            ],
        ),
    ]
