# Generated by Django 4.2.6 on 2023-10-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sabor_pizza',
            field=models.CharField(choices=[('Calabresa', 'Cs'), ('Mussarela', 'Ml'), ('Carne de Sol', 'CS'), ('Portuguesa', 'Ps'), ('Chocolate', 'Ct')], max_length=12, verbose_name='Sabor da Pizza'),
        ),
    ]
