# Generated by Django 4.2.6 on 2023-11-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_drink', models.CharField(max_length=50)),
                ('ml_drink', models.CharField(max_length=50)),
                ('quantidade_drink', models.IntegerField()),
                ('imagem_drink', models.ImageField(upload_to='./')),
                ('preco_drink', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RenameField(
            model_name='bebida',
            old_name='preco',
            new_name='preco_bebida',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='preco',
            new_name='preco_pizza',
        ),
        migrations.AlterField(
            model_name='bebida',
            name='ml_bebida',
            field=models.CharField(max_length=50),
        ),
    ]
