# Generated by Django 4.2.6 on 2023-10-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_pizza_sabor_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sabor_pizza',
            field=models.CharField(choices=[('Calabresa', '1'), ('Mussarela', '2'), ('Carne de Sol', '3'), ('Portuguesa', '4'), ('Chocolate', '5')], max_length=12, verbose_name='Sabor da Pizza'),
        ),
    ]
