# Generated by Django 4.2.6 on 2023-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_pizza_nome_pizza_alter_pizza_tamamho_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='borda_pizza',
            field=models.BooleanField(default=True, verbose_name='Com Borda'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamamho_pizza',
            field=models.CharField(choices=[('B', 'Brotinho'), ('M', 'Média'), ('p', 'pequena'), ('F', 'Família'), ('G', 'Grande')], max_length=1),
        ),
    ]
