# Generated by Django 4.2.6 on 2023-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_bebida_imagen_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tamamho_pizza',
            field=models.CharField(choices=[('F', 'Família'), ('G', 'Grande'), ('M', 'Média'), ('p', 'pequena'), ('B', 'Brotinho')], max_length=8, verbose_name='Tamanho da Pizza'),
        ),
    ]
