# Generated by Django 4.2.6 on 2023-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_pizza_borda_pizza_alter_pizza_tamamho_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='borda_pizza',
            field=models.BooleanField(blank=True, null=True, verbose_name='Com Borda'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamamho_pizza',
            field=models.CharField(choices=[('M', 'Média'), ('B', 'Brotinho'), ('F', 'Família'), ('p', 'pequena'), ('G', 'Grande')], max_length=1),
        ),
    ]
