# Generated by Django 4.2.6 on 2023-10-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_pizza_tamamho_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagen_pizza',
            field=models.ImageField(default=1, upload_to='foto_pizza/'),
            preserve_default=False,
        ),
    ]
