# Generated by Django 4.2.6 on 2023-10-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_imagem_pizza_pizza_imagen_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='imagen_pizza',
            new_name='imagem_pizza',
        ),
    ]
