# Generated by Django 4.2.6 on 2023-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_pizza_tamamho_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='descricao_pizza',
            field=models.TextField(verbose_name='Descrição da Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='quantidade_pizza',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sabor_pizza',
            field=models.CharField(max_length=50, verbose_name='Sabor da Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamamho_pizza',
            field=models.CharField(choices=[('B', 'Brotinho'), ('p', 'pequena'), ('G', 'Grande'), ('F', 'Família'), ('M', 'Média')], max_length=1, verbose_name='Tamanho da Pizza'),
        ),
    ]
