# Generated by Django 4.2.6 on 2023-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_pizza_imagem_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='imagem_pizza',
            field=models.ImageField(upload_to='./midia/foto_pizza'),
        ),
    ]
