# Generated by Django 4.2.6 on 2023-10-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_pizza_tamamho_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tamamho_pizza',
            field=models.CharField(choices=[('Família', 'F'), ('Grande', 'G'), ('Média', 'M'), ('pequena', 'p'), ('Brotinho', 'B')], max_length=8, verbose_name='Tamanho da Pizza'),
        ),
    ]
