# Generated by Django 4.2.6 on 2023-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_pizza_imagem_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='imagem_refri',
            field=models.ImageField(upload_to='./midia/foto_refri'),
        ),
    ]
