# Generated by Django 4.2.6 on 2023-10-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_alter_pizza_tamamho_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='add_pedido',
            new_name='adicionar_pedido',
        ),
    ]
