# Generated by Django 4.2.6 on 2023-10-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_delete_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionar_pedido', models.BooleanField(default=True)),
            ],
        ),
    ]
