# Generated by Django 4.2.6 on 2023-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='adicionar_pedido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
