# Generated by Django 4.2.6 on 2023-10-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='dadoscliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.dadoscliente'),
            preserve_default=False,
        ),
    ]
