# Generated by Django 4.2.6 on 2023-10-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_alter_pizza_tamamho_pizza'),
        ('cadastro', '0002_dadospessoais_dadoscliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscliente',
            name='bebida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.bebida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscliente',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscliente',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.pizza'),
            preserve_default=False,
        ),
    ]
