# Generated by Django 4.2.6 on 2023-10-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_dadoscliente_bebida_dadoscliente_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoscliente',
            name='pedido',
        ),
    ]
