# Generated by Django 4.2.6 on 2023-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_pizza_descricao_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tamamho_pizza',
            field=models.CharField(choices=[('G', 'Grande'), ('F', 'Família'), ('M', 'Média'), ('p', 'pequena'), ('B', 'Brotinho')], max_length=1, verbose_name='Tamanho da Pizza'),
        ),
    ]
