# Generated by Django 4.2.6 on 2023-10-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_dadoscliente_pedido'),
        ('biblioteca', '0009_rename_add_pedido_pedido_adicionar_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pedido',
        ),
    ]
